---
  - name: task 6 text manipulation
    hosts: all
    become: yes
    tasks: 
      - name: disable X11 Forwarding 
        lineinfile: 
          path: /etc/ssh/sshd_config
          regexp: 'X11Forwarding yes'
          line: 'X11Forwarding no'
          state: present
        notify: restart ssh
      - name: set max auth tries to 3
        lineinfile: 
          path: /etc/ssh/sshd_config
          regexp: '^MaxAuthTries '
          line: 'MaxAuthTries 3'
          state: present
        notify: restart ssh
    handlers:
      - name: restart ssh
        service: 
          name: sshd
          state: restarted
          enabled: yes
