---
  - name: task 18 templating
    hosts: all
    become: yes
    tasks: 
      - name: create /etc/hosts using template
        template:
          src: /home/automation/plays/templates/hosts.j2
          dest: /etc/hosts
          owner: root 
          group: root
          mode: 0644
          setype: net_conf_t
