---
  - name: task 8 create /etc/hosts/ like file
    hosts: all
    become: yes
    tasks: 
      - name: create /root/hosts using a template
        template: 
          src: templates/hosts.j2
          dest: /root/hosts_list.txt
        when: inventory_hostname in groups['dev'] or inventory_hostname in groups['qual']
